version: "3.1"
services:
  app:
    container_name: app
    hostname: localhost
    restart: always
    build: ${PWD}/app
    volumes:
      - ${PWD}/app/src:/opt/project:rw
    networks:
            my-network:
                aliases:
                    - flask-app
    command: gunicorn -b 0.0.0.0:8000 server:app --reload

    ports:
       - "8000:8000"

  nginx:
    container_name: nginx
    hostname: localhost
    build: ${PWD}/nginx
    depends_on:
            - app
    restart: always
    networks:
            - my-network
    ports:
      - "80:80"
      - "443:443"
networks:
    my-network:
